### ISSUE TITLE
what is reward_clip_thresholds??

### ISSUE THREAD

**Issue by TyrandeWhisperwind** [garlicdevs/Fruit-API#6]
i would like to know please, what is reward_clip_thresholds? and why it is set to None in MODQNLearner(DQNLearner)?
also do u have the algorithm to share with us of the MODQNLearner, so we can understand it better, cause in ur code their is no comments which makes it harder to guess how it works, thanks in advance

**Comment by TyrandeWhisperwind** [comment]
also where can i specify the weight of objectifs in MODQN?

**Comment by garlicdevs** [comment]
Hi,
You can see the example of using MODQN here
https://github.com/garlicdevs/Fruit-API/blob/master/fruit/samples/basic/multi_objectives_test.py

reward_clip_thresholds is used to clip the rewards if out of bound

**Comment by garlicdevs** [comment]
I implement it based on this paper
https://arxiv.org/abs/1803.02965

**Comment by TyrandeWhisperwind** [comment]
is it possible not to clip the rewards?

**Comment by garlicdevs** [comment]
Yes, just specify None

**Comment by TyrandeWhisperwind** [comment]
and if i want to add a new environment to solve my issue what should be changed in order to do so?

**Comment by garlicdevs** [comment]
In the example code, I implemented Deep Sea Treasure (DST) environment, you just check that code and develop your environment to replace the DST

**Comment by TyrandeWhisperwind** [comment]
thank you very much!!
