### ISSUE TITLE
Number of output and input in layer of networks

### ISSUE THREAD

**Issue by TyrandeWhisperwind** [garlicdevs/Fruit-API#7]
hello, wanted to ask u if possible, why did u choose this number of input and output in the layers?
  layer_1 = self.layer_manager.create_conv_layer(self.tf_inputs_norm, 32, 8, strides=4, activation_fn='relu',
                                                           padding='valid', scope='tf_layer_1')
  layer_2 = self.layer_manager.create_conv_layer(layer_1, 64, 4, strides=2, activation_fn='relu', padding='valid',
                                                           scope='tf_layer_2')
   layer_3 = self.layer_manager.create_conv_layer(layer_2, 64, 3, strides=1, activation_fn='relu', padding='valid',
                                                           scope='tf_layer_3')
   layer_4 = self.layer_manager.create_fully_connected_layer(layer_3, 512, activation_fn='relu',
                                                                      scope='tf_layer_4')
as i know the number of outputs in the output  layer should be  the number of possible actions in the environment, and the input is the state

**Comment by garlicdevs** [comment]
Hi, which file is this code in?

**Comment by TyrandeWhisperwind** [comment]
Fruit-API-master\fruit\configs\multi_objectives.py
and also why did u choose that number of neural in the hidden layers?

**Comment by garlicdevs** [comment]
The number of  hidden layers is based on this paper
https://arxiv.org/abs/1803.02965
It suits for Deep Sea Treasure, you can tune the network to suit your problem
