### ISSUE TITLE
FV is not in environment 

### ISSUE THREAD

**Issue by TyrandeWhisperwind** [garlicdevs/Fruit-API#9]
there is always this error occurring altho i did all the steps correctly 

![image](https://user-images.githubusercontent.com/45633853/87862811-f8ac6800-c94b-11ea-87a9-076ca09a7b60.png)

**Comment by garlicdevs** [comment]
I checked line 22 base.py: it is  self.state_space = environment.get_state_space() (not environment.FV)
Can you check your code
